name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:

  build:

    runs-on: self-hosted

    steps:
    - name: Pull Docker image
      run: sudo docker pull anupmaurya001/cicd-pipeline-docker:latest
    - name: Delete Old docker container
      run: sudo docker rm -f cicd-pipeline-container || true
    - name: Run Docker Container
      run: sudo docker run -d -p 3000:3000 --name cicd-pipeline-container -e MONGO_PASSWORD='${{ secrets.MONGO_PASSWORD }}' -e JWT_SECRET='${{ secrets.JWT_SECRET }}' anupmaurya001/cicd-pipeline-docker